version: '3.8'

services:
  ytmate:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - temp_data:/app/temp
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - WORKERS=4
      - TIMEOUT=120
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  temp_data: