version: '3.8'

services:
  ytmate:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - temp_data:/app/temp
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  temp_data: